/*TABLA CONTACTOS*/

insert into contactos (id, email, telefono, nombre) values (1, 'clinnock0@opensource.org', 10, 'aspergillus niger var. niger');
insert into contactos (id, email, telefono, nombre) values (2, 'jsamarth1@npr.org', 9, 'False Ragweed');
insert into contactos (id, email, telefono, nombre) values (3, 'krothert2@addthis.com', 9, 'Titanium Dioxide and Octinoxate');
insert into contactos (id, email, telefono, nombre) values (4, 'mcrankshaw3@imageshack.us', 9, 'Chloroxylenol');
insert into contactos (id, email, telefono, nombre) values (5, 'jockleshaw4@phpbb.com', 10, 'L-Menthol, Camphor');
insert into contactos (id, email, telefono, nombre) values (6, 'lstrickler5@bluehost.com', 10, 'aliskiren hemifumarate and hydrochlorothiazide');
insert into contactos (id, email, telefono, nombre) values (7, 'lcrut6@slashdot.org', 10, 'Calcium polycarbophil');
insert into contactos (id, email, telefono, nombre) values (8, 'wroget7@lycos.com', 9, 'flurbiprofen sodium');
insert into contactos (id, email, telefono, nombre) values (9, 'bknagges8@163.com', 10, 'carya tomentosa pollen and carya laciniosa pollen and carya ovata pollen and carya glabra pollen');
insert into contactos (id, email, telefono, nombre) values (10, 'wmacmaykin9@ow.ly', 10, 'Ibuprofen');
insert into contactos (id, email, telefono, nombre) values (11, 'jtringhama@reuters.com', 9, 'Metformin Hydrochloride');
insert into contactos (id, email, telefono, nombre) values (12, 'dastillb@deliciousdays.com', 9, 'Doxazosin Mesylate');
insert into contactos (id, email, telefono, nombre) values (13, 'lcasinec@scribd.com', 10, 'Piperonyl Butoxide, Pyrethrum Extract');
insert into contactos (id, email, telefono, nombre) values (14, 'saudreyd@unicef.org', 10, 'Norethindrone');
insert into contactos (id, email, telefono, nombre) values (15, 'ralleyne@flavors.me', 10, 'Octinoxate, Octisalate, and Oxybenzone');
insert into contactos (id, email, telefono, nombre) values (16, 'cruggierof@usatoday.com', 10, 'Clorazepate Dipotassium');
insert into contactos (id, email, telefono, nombre) values (17, 'areynardg@youtu.be', 10, 'Wingscale');
insert into contactos (id, email, telefono, nombre) values (18, 'ireadyh@google.com.au', 10, 'CALCITRIOL');
insert into contactos (id, email, telefono, nombre) values (19, 'alowniei@shinystat.com', 9, 'Dimethicone');
insert into contactos (id, email, telefono, nombre) values (20, 'mstolbergj@ow.ly', 9, 'alprazolam');

/*TABLA TIPO PROPIEDAD*/

insert into tipopropiedad (id, nombre) values (1, 'Departamento');
insert into tipopropiedad (id, nombre) values (2, 'Casa');
insert into tipopropiedad (id, nombre) values (3, 'Oficina');
insert into tipopropiedad (id, nombre) values (4, 'Terreno');
insert into tipopropiedad (id, nombre) values (5, 'Local');

/*TABLA TIPOUSUARIO*/

insert into tipousuario (id, nombre) values (1, 'Administrador');
insert into tipousuario (id, nombre) values (2, 'Usuario');

/*TABLA USUARIO*/

insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (1, 'Mélinda', 'Ragg', 'sragg0@usa.gov', 2, 'TP26NlSy', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (2, 'Görel', 'Carff', 'ecarff1@twitpic.com', 2, 'qTF14BK6Sew2', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (3, 'Marie-hélène', 'Alf', 'balf2@senate.gov', 2, '9J4Z8bIP45', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (4, 'Crééz', 'Stoves', 'qstoves3@ted.com', 2, 'WER2M4yVvumF', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (5, 'Mélanie', 'Coad', 'rcoad4@dion.ne.jp', 2, 'Sqqgjlhsz', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (6, 'Naelle', 'Sansome', 'csansome5@mac.com', 2, 'vW3CMkg8','1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (7, 'Pò', 'Sweetman', 'bsweetman6@hud.gov', 2, 'vW3CMkg8', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (8, 'Mahélie', 'Wildey', 'wwildey7@wisc.edu', 2, 'Tj668r8gG', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (9, 'Clémentine', 'Carlo', 'rcarlo8@slashdot.org', 2, 'ZYqGkfrq', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (10, 'Märta', 'Brixey', 'bbrixey9@msn.com', 2, 'fKSiJaVmTiA', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (11, 'Ruì', 'Heinzel', 'hheinzela@freewebs.com', 2, 'Aut2NXRTSsk', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (12, 'Mélina', 'Calveley', 'dcalveleyb@wisc.edu', 2, 'rFRtgG5s', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (13, 'Örjan', 'Pocklington', 'epocklingtonc@goo.ne.jp', 2, '6K72sJOAv', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (14, 'Cloé', 'Bramwich', 'dbramwichd@youtube.com', 2, '6K72sJOAv','1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (15, 'Miléna', 'Croker', 'acrokere@google.es', 2, 'MtCUIrQD', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (16, 'Desirée', 'Hamflett', 'ahamflettf@soup.io', 2, 'CLzgiY', '1616152108868_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (17, 'Gérald', 'Chansonnau', 'schansonnaug@taobao.com', 2, 'KKnjeesWW733', '1616152108867_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (18, 'Laurélie', 'Monger', 'omongerh@unc.edu', 2, 'BHQTnuqNPq1', '1616452991560_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (19, 'Annotés', 'Bestall', 'ebestalli@blinklist.com', 2, 'YmQNFF', '1616452991560_img.jpg');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (20, 'Mariano', 'Ramos', 'marianojramos1@yahoo.com.ar', 1, '$2a$10$IeniQQnRLyyj266yM29Cu.jbmOzTtTFhjfajm8LWm2qxlB28ZRGO.', '1617967834834_img.png');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) values (21, 'Hernan', 'Minore', 'hernan@yahoo.com.ar', 1, '$2a$10$IeniQQnRLyyj266yM29Cu.jbmOzTtTFhjfajm8LWm2qxlB28ZRGO.', '1617967834834_img.png');
insert into usuario (id, nombre, apellido, email, tipo_usuario, password, imagen) VALUES (22, 'Martin', 'Richielo', 'martin@yahoo.com.ar', 1, '$2a$10$IeniQQnRLyyj266yM29Cu.jbmOzTtTFhjfajm8LWm2qxlB28ZRGO.', '1617967834834_img.png');

/*TABLA PROPIEDAD*/
insert into propiedad (id, titulo, estado, tipoopercion, tipopropiedad_id, precio, direccion, barrio, latitud, longitud, descripciongral, suptotal, supcubierta, supdescubierta, ambientes, dormitorios, banios, medcocina, tipococina, lavadero, balcon, baulera, palier, recepcion, calefaccion, aire, expensas, abl, tipopiso, nropisos, dptosxpisos, ascensor, gimnasio, lavaderocen, sum, solarium, salonfiestas, guardabici, piscina, quincho, parrilla, seguridad, grupoelec, youtube, vimeo, plano, fotos) values (1, 'Cordoba Av. 1100', 'Activo', 'alquiler', 2, '650000', 'Cordoba Av. 1100', 'Retiro', 22.6166667, 6.300757, 'Semipiso. 2 dormitorio(s). 1 baño(s) 1 toilette(s).Habitación de servicio. Entre medianeras. Al frente. S/av. principal. Reciclado. En muy buen estado. Antigüedad 80 años.', 22416, 2263, 95964, 1, 2, 1, '2 x 3', 'americana', 'true', 'false', 'true', 'false', 'true', 'true', 'false', 122221, 1200, 'Piso completo', 2, 1, 2, 'true', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'false', 'V4394XD', 'I70711', 'planos-1615244431553.jpg', 'fotos-1615244431572.jpg');
insert into propiedad (id, titulo, estado, tipoopercion, tipopropiedad_id, precio, direccion, barrio, latitud, longitud, descripciongral, suptotal, supcubierta, supdescubierta, ambientes, dormitorios, banios, medcocina, tipococina, lavadero, balcon, baulera, palier, recepcion, calefaccion, aire, expensas, abl, tipopiso, nropisos, dptosxpisos, ascensor, gimnasio, lavaderocen, sum, solarium, salonfiestas, guardabici, piscina, quincho, parrilla, seguridad, grupoelec, youtube, vimeo, plano, fotos) values (2, 'Juncal 700', 'Activo', 'alquiler', 2, '650000', 'Juncal 700', 'Recoleta', 22.6166667, 6.300757, 'Edificio Racionalista. Piso al frente con vista al Palacio Estrugamou. Living, comedor, tres dormitorios y dos baños. Cocina con comedor diario, lavadero y dependencia de servicio. Pisos de parquet. Departamento en muy buen estado. Luminoso. Bien ubicado, en una de las calles más lindas del barrio de Retiro.', 22416, 2263, 95964, 1, 2, 1, '2 x 3', 'americana', 'true', 'false', 'true', 'false', 'true', 'true', 'false', 500400, 1200, 'Piso completo', 2, 1, 2, 'true', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'false', 'V4394XD', 'I70711', 'planos-1615244431553.jpg', 'fotos-1615244431572.jpg');
insert into propiedad (id, titulo, estado, tipoopercion, tipopropiedad_id, precio, direccion, barrio, latitud, longitud, descripciongral, suptotal, supcubierta, supdescubierta, ambientes, dormitorios, banios, medcocina, tipococina, lavadero, balcon, baulera, palier, recepcion, calefaccion, aire, expensas, abl, tipopiso, nropisos, dptosxpisos, ascensor, gimnasio, lavaderocen, sum, solarium, salonfiestas, guardabici, piscina, quincho, parrilla, seguridad, grupoelec, youtube, vimeo, plano, fotos) values (3, 'Cerrito 1500', 'Activo', 'alquiler', 2, '650000', 'Cerrito 1500', 'Retiro', 22.6166667, 6.300757, 'Semipiso. 2 dormitorio(s). 1 baño(s) 1 toilette(s).Habitación de servicio. Entre medianeras. Al frente. S/av. principal. Reciclado. En muy buen estado. Antigüedad 80 años.', 22416, 2263, 95964, 1, 2, 1, '2 x 3', 'americana', 'true', 'false', 'true', 'false', 'true', 'true', 'false', 6000, 1200, 'Piso completo', 2, 1, 2, 'true', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'false', 'V4394XD', 'I70711', 'planos-1615244431553.jpg', 'fotos-1615244431572.jpg');
insert into propiedad (id, titulo, estado, tipoopercion, tipopropiedad_id, precio, direccion, barrio, latitud, longitud, descripciongral, suptotal, supcubierta, supdescubierta, ambientes, dormitorios, banios, medcocina, tipococina, lavadero, balcon, baulera, palier, recepcion, calefaccion, aire, expensas, abl, tipopiso, nropisos, dptosxpisos, ascensor, gimnasio, lavaderocen, sum, solarium, salonfiestas, guardabici, piscina, quincho, parrilla, seguridad, grupoelec, youtube, vimeo, plano, fotos) values (4, 'Cerrito 800', 'Activo', 'alquiler', 2, '650000', 'Cerrito 800', 'Retiro', 22.6166667, 6.300757, 'Semipiso. 2 dormitorio(s). 1 baño(s) 1 toilette(s).Habitación de servicio. Entre medianeras. Al frente. S/av. principal. Reciclado. En muy buen estado. Antigüedad 80 años.', 22416, 2263, 95964, 1, 2, 1, '2 x 3', 'americana', 'true', 'false', 'true', 'false', 'true', 'true', 'false', 3000, 1800, 'Piso completo', 2, 1, 2, 'true', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'false', 'V4394XD', 'I70711', 'planos-1615244431553.jpg', 'fotos-1615244431572.jpg');
insert into propiedad (id, titulo, estado, tipoopercion, tipopropiedad_id, precio, direccion, barrio, latitud, longitud, descripciongral, suptotal, supcubierta, supdescubierta, ambientes, dormitorios, banios, medcocina, tipococina, lavadero, balcon, baulera, palier, recepcion, calefaccion, aire, expensas, abl, tipopiso, nropisos, dptosxpisos, ascensor, gimnasio, lavaderocen, sum, solarium, salonfiestas, guardabici, piscina, quincho, parrilla, seguridad, grupoelec, youtube, vimeo, plano, fotos) values (5, 'Talcahuano 900', 'Activo', 'alquiler', 2, '650000', 'Talcahuano 900', 'Retiro', 22.6166667, 6.300757, 'Semipiso. 2 dormitorio(s). 1 baño(s) 1 toilette(s).Habitación de servicio. Entre medianeras. Al frente. S/av. principal. Reciclado. En muy buen estado. Antigüedad 80 años.', 22416, 2263, 95964, 1, 2, 1, '2 x 3', 'americana', 'true', 'false', 'true', 'false', 'true', 'true', 'false', 26000, 1500, 'Piso completo', 2, 1, 2, 'true', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'false', 'V4394XD', 'I70711', 'planos-1615244431553.jpg', 'fotos-1615244431572.jpg');
insert into propiedad (id, titulo, estado, tipoopercion, tipopropiedad_id, precio, direccion, barrio, latitud, longitud, descripciongral, suptotal, supcubierta, supdescubierta, ambientes, dormitorios, banios, medcocina, tipococina, lavadero, balcon, baulera, palier, recepcion, calefaccion, aire, expensas, abl, tipopiso, nropisos, dptosxpisos, ascensor, gimnasio, lavaderocen, sum, solarium, salonfiestas, guardabici, piscina, quincho, parrilla, seguridad, grupoelec, youtube, vimeo, plano, fotos) values (6, 'Laprida Francisco Narciso 746 1°', 'Activo', 'alquiler', 2, '650000', 'Laprida Francisco Narciso 746 1°', 'Vicente López', 22.6166667, 6.300757, 'Semipiso. 2 dormitorio(s). 1 baño(s) 1 toilette(s).Habitación de servicio. Entre medianeras. Al frente. S/av. principal. Reciclado. En muy buen estado. Antigüedad 80 años.', 22416, 2263, 95964, 1, 2, 1, '2 x 3', 'americana', 'true', 'false', 'true', 'false', 'true', 'true', 'false', 122221, 3000, 'Piso completo', 2, 1, 2, 'true', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'false', 'V4394XD', 'I70711', 'planos-1615244431553.jpg', 'fotos-1615244431572.jpg');
insert into propiedad (id, titulo, estado, tipoopercion, tipopropiedad_id, precio, direccion, barrio, latitud, longitud, descripciongral, suptotal, supcubierta, supdescubierta, ambientes, dormitorios, banios, medcocina, tipococina, lavadero, balcon, baulera, palier, recepcion, calefaccion, aire, expensas, abl, tipopiso, nropisos, dptosxpisos, ascensor, gimnasio, lavaderocen, sum, solarium, salonfiestas, guardabici, piscina, quincho, parrilla, seguridad, grupoelec, youtube, vimeo, plano, fotos) values (7, 'Alvear Marcelo T. De 2300', 'Activo', 'alquiler', 2, '650000', 'Alvear Marcelo T. De 2300', 'Recoleta', 22.6166667, 6.300757, 'Semipiso. 2 dormitorio(s). 1 baño(s) 1 toilette(s).Habitación de servicio. Entre medianeras. Al frente. S/av. principal. Reciclado. En muy buen estado. Antigüedad 80 años.', 22416, 2263, 95964, 1, 2, 1, '2 x 3', 'americana', 'true', 'false', 'true', 'false', 'true', 'true', 'false', 15000, 2000, 'Piso completo', 2, 1, 2, 'true', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'false', 'V4394XD', 'I70711', 'planos-1615244431553.jpg', 'fotos-1615244431572.jpg');
insert into propiedad (id, titulo, estado, tipoopercion, tipopropiedad_id, precio, direccion, barrio, latitud, longitud, descripciongral, suptotal, supcubierta, supdescubierta, ambientes, dormitorios, banios, medcocina, tipococina, lavadero, balcon, baulera, palier, recepcion, calefaccion, aire, expensas, abl, tipopiso, nropisos, dptosxpisos, ascensor, gimnasio, lavaderocen, sum, solarium, salonfiestas, guardabici, piscina, quincho, parrilla, seguridad, grupoelec, youtube, vimeo, plano, fotos) values (8, 'Arenales 900', 'Activo', 'alquiler', 2, '650000', 'Arenales 900', 'Retiro', 22.6166667, 6.300757, 'Espectacular edificio estilo Francés. Es un piso al frente, 186.77 metros totales, luminoso. Pisos originales de parquet de roble. Cuenta con Hall, living y comedor a balcón, escritorio, tres dormitorios, el principal en suite, 2 baños completos, habitación y baño de servicio, lavadero independiente.', 22416, 2263, 95964, 1, 2, 1, '2 x 3', 'americana', 'true', 'false', 'true', 'false', 'true', 'true', 'false', 12000, 8000, 'Piso completo', 2, 1, 2, 'true', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'false', 'V4394XD', 'I70711', 'planos-1615244431553.jpg', 'fotos-1615244431572.jpg');
insert into propiedad (id, titulo, estado, tipoopercion, tipopropiedad_id, precio, direccion, barrio, latitud, longitud, descripciongral, suptotal, supcubierta, supdescubierta, ambientes, dormitorios, banios, medcocina, tipococina, lavadero, balcon, baulera, palier, recepcion, calefaccion, aire, expensas, abl, tipopiso, nropisos, dptosxpisos, ascensor, gimnasio, lavaderocen, sum, solarium, salonfiestas, guardabici, piscina, quincho, parrilla, seguridad, grupoelec, youtube, vimeo, plano, fotos) values (9, 'Viamonte 600', 'Activo', 'alquiler', 2, '650000', 'Viamonte 600', 'Retiro', 22.6166667, 6.300757, 'Semipiso. 2 dormitorio(s). 1 baño(s) 1 toilette(s).Habitación de servicio. Entre medianeras. Al frente. S/av. principal. Reciclado. En muy buen estado. Antigüedad 80 años.', 22416, 2263, 95964, 1, 2, 1, '2 x 3', 'americana', 'true', 'false', 'true', 'false', 'true', 'true', 'false', 122333, 1200, 'Piso completo', 2, 1, 2, 'true', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'false', 'V4394XD', 'I70711', 'planos-1615244431553.jpg', 'fotos-1615244431572.jpg');
insert into propiedad (id, titulo, estado, tipoopercion, tipopropiedad_id, precio, direccion, barrio, latitud, longitud, descripciongral, suptotal, supcubierta, supdescubierta, ambientes, dormitorios, banios, medcocina, tipococina, lavadero, balcon, baulera, palier, recepcion, calefaccion, aire, expensas, abl, tipopiso, nropisos, dptosxpisos, ascensor, gimnasio, lavaderocen, sum, solarium, salonfiestas, guardabici, piscina, quincho, parrilla, seguridad, grupoelec, youtube, vimeo, plano, fotos) values (10, 'Cabral Sgto. 800', 'Activo', 'alquiler', 2, '650000', 'Cabral Sgto. 800', 'Retiro', 22.6166667, 6.300757, 'Excelente piso en edificio moderno entre medianeras. Piso al frente con mucha luz. Living de amplias dimensiones, comedor diario, escritorio y toilette. 4 dormitorios, 2 en suite, 3 baños. Cocina impecable con un agradable comedor de diario, lavadero y dos dependencias de servicio. Baulera,2 cocheras fijas. Grupo electrógeno. Su estado es de época. Orientación Este.', 22416, 2263, 95964, 1, 2, 1, '2 x 3', 'americana', 'true', 'false', 'true', 'false', 'true', 'true', 'false', 12500, 2000, 'Piso completo', 2, 1, 2, 'true', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'false', 'V4394XD', 'I70711', 'planos-1615244431553.jpg', 'fotos-1615244431572.jpg');

/*TABLA FAVORITOS*/

insert into favoritos (propiedad_id, usuario_id) values (1, 20);
insert into favoritos (propiedad_id, usuario_id) VALUES (2, 20);
insert into favoritos (propiedad_id, usuario_id) VALUES (3, 20);
insert into favoritos (propiedad_id, usuario_id) VALUES (1, 21);
insert into favoritos (propiedad_id, usuario_id) VALUES (4, 21);
insert into favoritos (propiedad_id, usuario_id) VALUES (5, 21);
insert into favoritos (propiedad_id, usuario_id) VALUES (5, 22);
insert into favoritos (propiedad_id, usuario_id) VALUES (8, 22);
insert into favoritos (propiedad_id, usuario_id) VALUES (9, 22);





